### ISSUE TITLE
FeatureFlag plugin does not support Configuration Cache

### ISSUE THREAD

**Issue by ganadist** [line/feature-flag-android#24]
`Configuration Cache`([link](https://docs.gradle.org/current/userguide/configuration_cache.html)) is a new (still experimental) gradle feature to improve build performance since Gradle 6.6

When `Configuration Cache` is enabled, gradle with `Feature Flag plugin` shows following error

```
- Task `:app:generateDebugFeatureFlag` of type `com.linecorp.android.featureflag.FeatureFlagTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

See the complete report at file:///home/user/MyProject/build/reports/configuration-cache/9i43owv2px0b29dm55tacf45w/5y0bvx624z6zaw9tntypso0nv/configuration-cache-report.html
> Invocation of 'Task.project' by task ':app:generateDebugFeatureFlag' at execution time is unsupported.

```

```
org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':app:generateDebugFeatureFlag' at execution time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:74)
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy307.onProjectAccess(Unknown Source)
	at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1053)
	at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:237)
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
	at com.linecorp.android.featureflag.FeatureFlagTask.action(FeatureFlagTask.kt:95)

```

See also https://github.com/gradle/gradle/issues/13490

**Comment by ganadist** [comment]
Since gradle 8.0, gradle warns that `getProject()` is deprecated and this will raise error since Gradle 9.0

```
Invocation of Task.project at execution time has been deprecated.
This will fail with an error in Gradle 9.0.

Task::featureflag:generateDevelopDebugFeatureFlag	
	at org.gradle.configurationcache.StableConfigurationCacheUnsupportedApiManagerAction$DeprecatedFeaturesListener.onProjectAccess(StableConfigurationCacheUnsupportedApiManagerAction.kt:71)	
	at java.lang.reflect.Method.invoke(Method.java:568)	
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:460)	
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:442)	
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)	
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)	
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:431)	
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:219)	
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:190)	
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
	at jdk.proxy1.$Proxy145.onProjectAccess(Unknown Source)	
	at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1049)	
	at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:232)	
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)	
	at com.linecorp.android.featureflag.FeatureFlagTask.action(FeatureFlagTask.kt:95)
```


https://docs.gradle.org/8.0.2/userguide/upgrading_version_7.html#task_project
